### PR TITLE
fix windows build

### PR DESCRIPTION
**Pull request by reklatsmasters**
Fix build for node 0.10.35.

### CODE REVIEW

**Comment by s-taylor** [comment]
This issue is also affecting me on OSX running node 0.10.35
npm install stalls when installing this module as a dependency of mongoose.

**Comment by christkv** [comment]
I've not been able to actually reproduce this issue. I suggest installing node 0.10.35 from source and if you have trouble you should attempt to clone the repo and build using node-gyp to see if something in your build environment is messed up. A lot of people have messed up build envs http://christiankvalheim.com/post/diagnose_installation_problems/

**Comment by Nicktho** [comment]
Hi Christian, 

I can't build kerberos running on OSX, node 0.10.35 or previous versions. 

I keep hitting this output and then stalling

```
> kerberos@0.0.4 install project_path/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)
```

I've followed all steps within your post and still hit the same errors, even while building from the source.

**Comment by s-taylor** [comment]
I can confirm it won't install on either node 0.10.34 or 0.10.35. On 0.10.33 I had no issues.

**Comment by christkv** [comment]
well kerberos@0.0.4 is really old I would suggest trying a newer version as there might be v8 api changes that requires a new kerberos version. I suggest trying 0.0.8 which is the latest shipping version for 1.4.29 and 2.0.14

**Comment by Nicktho** [comment]
Kerberos 0.0.4 is a dependency within the mongodb package.json

**Comment by christkv** [comment]
in an old driver version the fact that it broke between node versions points to a v8 c++ api issue

**Comment by christkv** [comment]
try to do npm cache clean

**Comment by s-taylor** [comment]
Issue seems to have been resolved by manually installing node-gyp globally

**Comment by christkv** [comment]
closed due to merging https://github.com/christkv/kerberos/issues/12

**Pull request closed without merging**
