### PR TITLE
Nan 2.0 Port

### PR DESCRIPTION
**Pull request by bazineta**
Port to nan 2.0

### CODE REVIEW

**Comment by steelbrain** [comment]
Dumb question but does it work with the latest node v4?

**Comment by bazineta** [comment]
So far as 'working', I don't know; as mentioned, I don't use this function at all.  However, it compiles against node v4.0 and the node-gyp that ships with it.

**Comment by steelbrain** [comment]
I can confirm that this works for me on node v4

**Comment by christkv** [comment]
it runs for node 4.0.0 but breaks on 0.12.x and 0.10.x unfortunately.

**Comment by steelbrain** [comment]
@christkv If I am not mistaken, node and iojs have merged and released 4.0.
People using old node can keep using the old versions. IMO that shouldn't be a blocker for this PR.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by christkv** [comment]
merged into this branch https://github.com/christkv/kerberos/tree/bazineta-master for now, minor fix to get it to compile on 0.10.x, 0.12.x and 4.0.0 but will have to wait until next week to test on windows. It it passes on window then we should be good. Has to support all major node production platforms.

**Pull request merged**
